services:
  gif-backend:
    build: .
    container_name: gif-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gifnet

networks:
  gifnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
